# set -g @catppuccin_flavor 'mocha'
#run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g @plugin 'fabioluciano/tmux-tokyo-night'
# set -g @plugin "nordtheme/tmux"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-strategy-nvim 'session'

# set -g @themepack 'basic'
set-option -g mouse on
set -g detach-on-destroy on

set -g default-terminal "alacritty"

set -sg terminal-overrides "*:RGB"

set-option -ga terminal-features ",alacritty:usstyle"

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

run '~/.tmux/plugins/tpm/tpm'

