$background = rgb(000006)
$foreground = rgb(FAEED6)
$color0 = rgb(0F1014)
$color1 = rgb(61414B)
$color2 = rgb(99464C)
$color3 = rgb(A7474C)
$color4 = rgb(56926E)
$color5 = rgb(89869F)
$color6 = rgb(B59B67)
$color7 = rgb(F0DFBC)
$color8 = rgb(A89C84)
$color9 = rgb(815764)
$color10 = rgb(CC5D65)
$color11 = rgb(DF5F65)
$color12 = rgb(73C393)
$color13 = rgb(B6B2D4)
$color14 = rgb(F1CF8A)
$color15 = rgb(F0DFBC)
