#!/bin/bash

config_folders=("godot" "ncspot" "wallust" "neofetch" "yazi" "mako" "rofi" "hypr" "spicetify" "waybar" "swaync" "alacritty" "qt5ct" "qt6ct" "nvim")

config_folder="$HOME/.config"

shampoo_zsh_theme="$HOME/.oh-my-zsh/themes/shampoo-shrek.zsh-theme"
zsharc_file="$HOME/.zshrc"

scripts_path="$HOME/Documents/DevOffice/scripts"

dotfiles_path="$HOME/Documents/dotfiles"

mkdir -p "$dotfiles_path/scripts"

for folder in "${config_folders[@]}"; do
	mkdir -p "$dotfiles_path/.config/$folder/"
done

cp "$shampoo_zsh_theme" "$dotfiles_path/shell"

cp "$zsharc_file" "$dotfiles_path/shell"

cp -r "$scripts_path" "$dotfiles_path"

for folder in "${config_folders[@]}"; do
	cp -r "$config_folder/$folder" "$dotfiles_path/.config"
done
