return {}
--   {
--     "iabdelkareem/csharp.nvim",
--     dependencies = {
--       "williamboman/mason.nvim", -- Required, automatically installs omnisharp
--       "mfussenegger/nvim-dap",
--       "Tastyep/structlog.nvim", -- Optional, but highly recommended for debugging
--     },
--     config = function()
--       require("mason").setup() -- Mason setup must run before csharp, only if you want to use omnisharp
--       require("csharp").setup()
--     end,
--     recommended = function()
--       return LazyVim.extras.wants({
--         ft = { "cs", "vb" },
--         root = { "*.sln", "*.csproj", "function.json" },
--       })
--     end,
--   },
--   -- { "Hoffs/omnisharp-extended-lsp.nvim", lazy = true },
--   {
--     "nvim-treesitter/nvim-treesitter",
--     opts = { ensure_installed = { "c_sharp" } },
--   },
-- }
